version: '3'
services:
  eureka-discovery:
    container_name: eureka-discovery
    image: eureka-server
    build: ./eureka-discovery
    #restart: always
    expose:
      - 8761
    ports:
      - 8761:8761

  config-server:
    image: config-server
    container_name: config-server
    build: ./config-server
    #restart: always
    expose:
      - 8888
    links:
      - eureka-discovery
    ports:
      - 8888:8888
    depends_on:
      - eureka-discovery
    environment:
      server.port: 8888
      eureka.client.enabled: 'true'
      eureka.host: eureka-discovery
      eureka.instance.preferIpAddress: 'true'

  auth-service:
    image: oauth-service
    container_name: auth-service
    build: ./auth-service
    #restart: always
    expose:
      - 9000
    ports:
      - 9000:9000
    links:
      - eureka-discovery
      - config-server
    depends_on:
      - eureka-discovery
      - config-server
    environment:
      server.port: 9000
      eureka.client.enabled: 'true'
      eureka.host: eureka-discovery
      eureka.instance.preferIpAddress: 'true'
      spring.cloud.config.enabled: 'true'
      spring.cloud.config.service-id: config-server

  customer-service:
    image: customer-service
    container_name: customer-service
    build: ./customer-service
    #restart: always
    expose:
      - 7070
    ports:
      - 7070:7070
    links:
      - eureka-discovery
      - config-server
      - auth-service
    depends_on:
      - eureka-discovery
      - config-server
    environment:
      server.port: 7070
      eureka.client.enabled: 'true'
      eureka.host: eureka-discovery
      eureka.instance.preferIpAddress: 'true'
      spring.cloud.config.enabled: 'true'
      spring.cloud.config.service-id: config-server

  dashboard-service:
    image: dashboard-service
    container_name: dashboard-service
    build: ./dashboard-service
    #restart: always
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - eureka-discovery
      - config-server
      - auth-service
      - customer-service
    depends_on:
      - eureka-discovery
      - config-server
    environment:
      server.port: 9090
      eureka.client.enabled: 'true'
      eureka.host: eureka-discovery
      eureka.instance.preferIpAddress: 'true'
      spring.cloud.config.enabled: 'true'
      spring.cloud.config.service-id: config-server

  gateway-service:
    image: gateway-service
    container_name: gateway-service
    build: ./gateway-service
    #restart: always
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - eureka-discovery
      - config-server
      - auth-service
      - customer-service
      - dashboard-service
    depends_on:
      - eureka-discovery
      - config-server
    environment:
      server.port: 8080
      eureka.client.enabled: 'true'
      eureka.host: eureka-discovery
      eureka.instance.preferIpAddress: 'true'
      spring.cloud.config.enabled: 'true'
      spring.cloud.config.service-id: config-server
